resilience4j:
  retry:
    instances:
      sample-retry:
        enable-exponential-backoff: true
        max-attempts: 5
        wait-duration: 1s
  ratelimiter:
    instances:
      default:
        limit-refresh-period: 10s
        limit-for-period: 2
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 2
server:
  port: 8000
spring:
  application:
    name: currency-exchange-service
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  sleuth:
    sampler:
      probability: 1.0
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true